export const strings = {
  common: {
    appName: 'SSBMax',
    appTagline: 'Armed Forces Selection Board Preparation Platform',
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Retry',
    cancel: 'Cancel',
    save: 'Save',
    submit: 'Submit',
    close: 'Close',
    back: 'Back',
    next: 'Next'
  },
  header: {
    title: 'SSBMax',
    tagline: 'SSB Prep',
    toggleThemeDark: 'Switch to Dark Mode',
    toggleThemeLight: 'Switch to Light Mode',
    statusOnline: 'Online',
    statusOffline: 'Offline',
    installPwa: 'Install App',
    signIn: 'Sign In',
    signOut: 'Sign Out'
  },
  auth: {
    signInWithGoogle: 'Sign in with Google',
    signOut: 'Sign Out',
    welcomeBack: 'Welcome back,',
    authError: 'Authentication failed. Please try again.'
  },
  oir: {
    title: 'Officer Intelligence Rating (OIR)',
    instructions: 'Complete 50 questions within the timed window.',
    timerLabel: 'Time Remaining',
    questionCount: 'Question {current} of {total}',
    submitTest: 'Submit Test',
    submitting: 'Submitting test answers...',
    requiresOnline: 'OIR score evaluation requires online connection.',
    completedTitle: 'OIR Test Completed',
    scoreLabel: 'Your Score',
    ratingLabel: 'OIR Rating',
    noQuestions: 'No questions available'
  },
  psychology: {
    tatTitle: 'Thematic Apperception Test (TAT)',
    watTitle: 'Word Association Test (WAT)',
    srtTitle: 'Situation Reaction Test (SRT)',
    ppdtTitle: 'Picture Perception & Discussion Test (PPDT)',
    sdTitle: 'Self Description (SD)',
    slideTimer: 'Slide Time',
    requiresOnline: 'AI Evaluation requires active internet connection.',
    writeResponsePlaceholder: 'Write your story / response here...',
    nextSlide: 'Next Slide',
    finishTest: 'Complete & Submit',
    completedTitle: 'Psychology Test Completed',
    completedMessage: 'Your responses have been recorded and sent for AI evaluation.'
  },
  payment: {
    upgradeTitle: 'Unlock Pro Membership',
    upgradeDescription: 'Get unlimited AI evaluations for TAT, WAT, SRT, and Mock Interviews.',
    payButton: 'Upgrade Now with Razorpay',
    paymentSuccess: 'Payment successful! Access granted.',
    paymentFailed: 'Payment verification failed.'
  },
  subscription: {
    title: 'Officer Pass Membership Tiers',
    subtitle: 'Choose your subscription plan to unlock full Gemini 2.5 AI psychological dossier evaluations and unlimited SSB test batteries.',
    freePlanTitle: 'Free Cadet Pass',
    freePlanPrice: '₹0 / Month',
    freePlanBadge: 'FREE',
    freeFeature1: 'Stage I OIR Test Simulators',
    freeFeature2: 'Basic Practice Tests',
    freeFeature3: 'Cached Study Materials',
    currentPlan: 'Current Active Plan',
    proPlanTitle: 'Pro Officer Pass',
    proPlanPrice: '₹499 / Month',
    proPlanBadge: 'MOST POPULAR',
    proFeature1: 'Unlimited Stage II Psych Batteries (TAT, WAT, SRT, SD)',
    proFeature2: 'Gemini 2.5 Flash AI Assessor Dossier Reports',
    proFeature3: '15 Officer-Like Qualities (OLQ) Radar Analytics',
    proFeature4: 'Stage I PPDT Canvas & Narration Practice',
    proFeature5: 'Priority Assessor Feedback & Cloud Sync',
    upgradeNow: 'Upgrade to Officer Pass',
    processing: 'Processing Order...',
    successBadge: 'Pro Officer Pass Active',
    successMessage: 'Welcome to Pro Membership! Access unlocked across all AI evaluation engines.',
    guarantee: '100% Refund Policy & Secure 256-Bit Razorpay Encryption'
  },
  offline: {
    queuedMessage: 'Test response saved offline. Will sync when back online.',
    reconnectNotice: 'You are currently offline. Local cache enabled.'
  },
  studyMaterial: {
    title: 'Free Study Material',
    allCategories: 'All Categories',
    readTime: '{min} min read',
    markAsRead: 'Mark as Read',
    completed: 'Completed',
    noMaterials: 'No study materials available at the moment.',
    loadError: 'Failed to load study materials.',
    offlineNotice: 'Viewing cached study material'
  },
  olq: {
    scoreCardTitle: 'Officer-Like Qualities (OLQ) Assessment',
    factor1: 'Factor I: Intellectual Qualities',
    factor2: 'Factor II: Social Qualities',
    factor3: 'Factor III: Dynamic Qualities',
    factor4: 'Factor IV: Character & Physical Qualities',
    recommendations: 'Key Recommendations & Improvement Areas',
    overallConfidence: 'Overall Assessment Confidence',
    scoreFormat: 'Score: {score} / 10',
    noScores: 'No OLQ scores available.'
  },
  nav: {
    dashboard: 'Command Center',
    landing: 'Home',
    practice: 'Practice Tests',
    study: 'Study Material',
    reports: 'AI Reports',
    pricing: 'Officer Pass',
    account: 'Account',
    settings: 'Settings'
  },
  landing: {
    heroBadge: 'AI-Powered SSB Intelligence Platform',
    heroTitle: 'Master the Services Selection Board with AI Precision',
    heroSubtitle: 'Comprehensive Stage-I Screening, Stage-II Psychology Battery (TAT, WAT, SRT, SD), and Gemini 2.5 Flash AI Dossier Evaluation with 15 OLQ Analytics.',
    startFree: 'Start Free OIR Test',
    unlockPro: 'Unlock Pro Officer Pass',
    statOlq: '15 Officer Like Qualities',
    statStage: '5-Day SSB Coverage',
    statAi: 'Gemini 2.5 AI Analysis',
    featureTitle: 'Complete Selection Board Suite',
    featureSubtitle: 'Trained on standardized Defence Selection Board guidelines for Army, Navy, and Air Force aspirants.'
  },
  dashboard: {
    title: 'Candidate Command Center',
    subtitle: 'Track your preparation progress, run timed SSB test simulators, and review AI OLQ assessments.',
    readinessScore: 'SSB Readiness Score',
    readinessIndex: 'SSB Officer Readiness Index',
    stage1Title: 'Stage I: Screening Battery',
    stage1Sub: 'Officer Intelligence Rating (OIR) & Picture Perception & Discussion Test (PPDT)',
    stage2Title: 'Stage II: Psychology Tests',
    stage2Sub: 'Thematic Apperception (TAT), Word Association (WAT), Situation Reaction (SRT), Self Description (SD)',
    recentReports: 'Recent AI Dossier Reports',
    noReports: 'No AI test reports generated yet. Complete a Psychology test to receive your 15 OLQ evaluation.',
    launchStage1: 'Launch Stage I Simulators',
    launchStage2: 'Launch Stage II Battery',
    viewFullReport: 'View Full AI Report',
    targetBoard: 'Target Board',
    entryStream: 'Entry Stream',
    prepStatus: 'Preparation Status',
    editProfile: 'Edit Diagnostic Profile',
    startOirSim: 'Start OIR Simulator',
    startPpdtSim: 'Start PPDT Simulator',
    startPsychBattery: 'Start Full Psych Battery'
  },
  diagnostic: {
    title: 'Candidate Diagnostic Onboarding',
    subtitle: 'Tailor your SSB preparation profile for precision AI analysis.',
    targetBoardLabel: 'Target SSB Board',
    entryTypeLabel: 'Entry Stream',
    prepLevelLabel: 'Current Preparation Status',
    targetDateLabel: 'Target SSB Month',
    boardArmy: 'Indian Army (SSB)',
    boardNavy: 'Indian Navy (NSB)',
    boardAirForce: 'Air Force (AFSB)',
    entryNda: 'NDA (National Defence Academy)',
    entryCds: 'CDS (Combined Defence Services)',
    entryAfcat: 'AFCAT (Air Force Common Admission Test)',
    entryTesTgc: 'TES / TGC Technical Entry',
    entryNcc: 'NCC Special Entry',
    prepBeginner: 'Beginner (First SSB Attempt)',
    prepIntermediate: 'Intermediate (1-2 SSBs)',
    prepAdvanced: 'Repeater / Advanced Prep',
    saveProfile: 'Save & Continue to Command Center',
    skipModal: 'Skip for Now',
    editDiagnostic: 'Edit Profile Diagnostic',
    profileSaved: 'Diagnostic profile updated successfully.'
  },
  radar: {
    title: '15 Officer Like Qualities (OLQ) Radar Profile',
    subtitle: 'Interactive 15-axis assessment polygon mapping candidate scores against baseline thresholds.',
    candidateScore: 'Candidate Score',
    benchmarkLabel: 'SSB Baseline Threshold (7.0)',
    selectOlqHint: 'Click or hover over an OLQ point to view detailed assessment reasoning.',
    noData: 'No OLQ radar dataset available.'
  },
  dossier: {
    title: 'Military Psychologist AI Dossier',
    classification: 'CONFIDENTIAL // FOR OFFICIAL ASSESSOR USE ONLY',
    candidateIdLabel: 'Candidate ID',
    assessedDateLabel: 'Assessment Date',
    overallStatusLabel: 'Psychological Recommendation Status',
    statusRecommended: 'RECOMMENDED FOR SELECTION BOARD',
    statusBorderline: 'BORDERLINE / REQUIRES CONFERENCE PROBE',
    statusNotRecommended: 'NOT RECOMMENDED AT PRESENT',
    summaryTitle: 'Executive Psychological Overview',
    strengthsTitle: 'Observed Key Strengths',
    concernsTitle: 'Areas of Concern / Red Flags',
    probesTitle: 'Suggested Interview & GTO Probes',
    noData: 'No Psychologist Dossier available. Complete a psychology battery test to generate.'
  },
  account: {
    title: 'Candidate Account Profile',
    subtitle: 'Manage your SSB candidate profile, subscription status, and target board credentials.',
    candidateDetails: 'Candidate Profile Details',
    displayName: 'Full Name',
    email: 'Email Address',
    authStatus: 'Authentication Status',
    signedIn: 'Authenticated Officer Cadet',
    guestUser: 'Guest Cadet',
    membershipTier: 'Active Pass Membership',
    uidLabel: 'Candidate UID',
    targetBoard: 'Target SSB Board',
    entryStream: 'Entry Stream',
    prepStatus: 'Preparation Stage',
    editDiagnostic: 'Edit Profile',
    upgradeTier: 'Upgrade Pass',
    signOut: 'Sign Out Account'
  },
  settings: {
    title: 'Candidate Command Settings',
    subtitle: 'Configure theme preferences, notification triggers, and offline data caching.',
    appearanceTitle: 'Appearance & Display Theme',
    appearanceSub: 'Toggle between Tactical Dark Mode and Officer Light Mode.',
    themeLabel: 'Current Active Theme',
    themeDark: 'Tactical Dark Mode',
    themeLight: 'Officer Light Mode',
    notificationsTitle: 'Notification & Intelligence Sync',
    notificationsSub: 'Manage test reminders, AI report notifications, and offline sync alerts.',
    emailAlerts: 'Email AI Report Dossiers',
    offlineSyncAlerts: 'Offline Queue Sync Alerts',
    practiceReminders: 'Daily SSB Practice Reminders',
    dataStorageTitle: 'Data & Offline Cache',
    dataStorageSub: 'Manage local data cache and offline test submissions.',
    clearCache: 'Clear Local Cache',
    cacheCleared: 'Local cache cleared successfully.',
    systemTitle: 'Platform & Environment Diagnostics',
    systemSub: 'Verify SSBMax web application build version and PWA connectivity.',
    appVersion: 'Platform Version',
    pwaStatus: 'PWA Connectivity',
    onlineStatus: 'Network Connection Status'
  }
} as const;
