package com.ssbmax.core.domain.model.interview

/**
 * Interview question model
 *
 * @param id Unique question identifier
 * @param questionText The question to be asked
 * @param expectedOLQs List of OLQs this question is designed to assess
 * @param context Additional context or follow-up information
 * @param source Question source (PIQ-based, generic pool, or AI-generated)
 */
data class InterviewQuestion(
    val id: String,
    val questionText: String,
    val expectedOLQs: List<OLQ>,
    val context: String? = null,
    val source: QuestionSource
)

/**
 * Source of the interview question
 */
enum class QuestionSource {
    PIQ_BASED,      // Generated from candidate's PIQ data
    GENERIC_POOL,   // From Firestore generic question pool
    AI_GENERATED    // Generated by Gemini AI during interview
}
